var sarr = [
['Organic Search','Google','Web','www.google.com','',[]]
,['Organic Search','Bing','Web','www.bing.com/','',[]]
,['Organic Search','Yahoo','Web','search.yahoo.com','',[]]
,['Organic Search','Ask.Com','Web','www.ask.com','',[]]
,['Paid Search','Google','Paid Media','','utm_source=google',[]]
,['Paid Search','Google','Paid Media','','gclid=',[]]
,['Paid Search','Bing','Paid Media','','utm_source=bing',[]]
,['Paid Search','Yahoo','Paid Media','/cbclk2/','utm_source=gemini',[]]
,['Paid Search','Yahoo','Paid Media','search.yahoo.com','_ylt=',[]]
,['Organic Social','Blog','Web','','',[]]
,['Organic Social','Facebook','Web','www.facebook.com','',[]]
,['Organic Social','Twitter','Web','t.co/','',[]]
,['Organic Social','Linkedin','Web','www.linkedin.com','d_flagship3_search_srp_top',[]]
,['Organic Social','Linkedin','Web','','d_flagship3_feed',[]]
,['Paid Social','Facebook','Paid Media','l.facebook.com','utm_source=facebook',[]]
,['Paid Social','Twitter','Paid Media','','utm_source=twitter.com',[]]
,['Paid Social','LinkedIn','Paid Media','bit.ly/','utm_source=LinkedIn',[]]
,['Referral','Other Sites','External','','',[]]
,['Referral','Partners','Partner','','',[]]
,['Misc','Press Rel','PR','','',[]]
,['Misc','Direct Web','Web','','',[]]
];
